name: Main
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          TAG=main
          acorn login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          acorn build --push -p linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:$TAG .